### ISSUE TITLE
cant install aws plugin

### ISSUE THREAD

**Issue by amitgilad3** [elasticsearch/puppet-elasticsearch#230]
Hi ,
i am trying to install the aws plugin for my elasticsearch and i get the following error 

Error: Failed to apply catalog: Could not find dependent Elasticsearch::Service[elasticsearch-ddna83ab1gx88h8] for Exec[install_plugin_elasticsearch/elasticsearch-cloud-aws/2.4.1] at /etc/puppet/modules/elasticsearch/manifests/plugin.pp:96

this is my puppet code:

class { 'elasticsearch':
  package_url => 'https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.2.noarch.rpm',
  datadir => '/media/ephemeral0/elastic',
}->
elasticsearch::plugin{'elasticsearch/elasticsearch-cloud-aws/2.4.1':
  module_dir => 'elasticsearch',
  instances  => 'elasticsearch',
}

can you please tell me what am i doing wrong??

**Comment by electrical** [comment]
Hi,

in this case you don't have an instance defined. since by default we don't create a default one you will need to specify one.
See https://github.com/elasticsearch/puppet-elasticsearch#instances for more information.
You also won't need specify the relation / sequence using the `->` since we handle that internally in the module already.

Also the module_dir is the directory that gets created by the module it self.
In this case cloud-aws.
I'm still looking for a better solution since its only used to validate if the plugin is installed or not.

If you have any further questions let me know. I'm also available on the Elasticsearch IRC channel on Freenode.
